import fs from 'node:fs';
const financePath = '/home/ubuntu/controle-financeiro-familiar/shared/finance.ts';
let finance = fs.readFileSync(financePath, 'utf8');
finance = finance.replace('export function summarizeTransactions(transactions: FinanceTransaction[]) {', 'export function removeTransactionScope<T extends { id: number; installmentGroupId?: string }>(transactions: T[], target: T, scope: "item" | "group") {\n  return transactions.filter((item) => scope === "group" && target.installmentGroupId ? item.installmentGroupId !== target.installmentGroupId : item.id !== target.id);\n}\n\nexport function summarizeTransactions(transactions: FinanceTransaction[]) {');
fs.writeFileSync(financePath, finance);

const homePath = '/home/ubuntu/controle-financeiro-familiar/client/src/pages/Home.tsx';
let home = fs.readFileSync(homePath, 'utf8');
home = home.replace('import { aggregateMonthly, filterTransactions, installmentDate, splitInstallments, summarizeTransactions } from "@shared/finance";', 'import { aggregateMonthly, filterTransactions, installmentDate, removeTransactionScope, splitInstallments, summarizeTransactions } from "@shared/finance";');
home = home.replace('<button onClick={() => item.installmentGroupId ? onDeleteGroup(item.installmentGroupId) : onDelete(item.id)} className="rounded-lg p-2 text-[#83938b] hover:bg-[#f8e8e5] hover:text-[#a55348]" aria-label={item.installmentGroupId ? "Excluir compra parcelada" : "Excluir"} title={item.installmentGroupId ? "Excluir todas as parcelas" : "Excluir"}><Trash2 className="h-4 w-4" /></button>', '{item.installmentGroupId ? <><button onClick={() => onDelete(item.id)} className="rounded-lg p-2 text-[#83938b] hover:bg-[#f8e8e5] hover:text-[#a55348]" aria-label="Excluir esta parcela" title="Excluir esta parcela"><Trash2 className="h-4 w-4" /></button><button onClick={() => onDeleteGroup(item.installmentGroupId!)} className="rounded-lg p-2 text-[#a55348] hover:bg-[#f8e8e5]" aria-label="Excluir todas as parcelas" title="Excluir todas as parcelas"><Trash2 className="h-4 w-4" /></button></> : <button onClick={() => onDelete(item.id)} className="rounded-lg p-2 text-[#83938b] hover:bg-[#f8e8e5] hover:text-[#a55348]" aria-label="Excluir" title="Excluir"><Trash2 className="h-4 w-4" /></button>}');
home = home.replace('const deleteTransaction = (id: number) => { setTransactions((current) => current.filter((item) => item.id !== id)); toast.success("Lançamento removido."); };', 'const deleteTransaction = (id: number) => { setTransactions((current) => current.filter((item) => item.id !== id)); toast.success("Lançamento removido."); };');
fs.writeFileSync(homePath, home);
