import fs from 'node:fs';
const path = '/home/ubuntu/controle-financeiro-familiar/client/src/pages/Home.tsx';
let s = fs.readFileSync(path, 'utf8');
s = s.replace('function TransactionsView({ transactions, onDelete, onDeleteGroup, onUpdate, categoriesData, payments }: { transactions: Transaction[]; onDelete: (id: number) => void; onDeleteGroup: (groupId: string) => void; onUpdate: (transaction: Transaction) => void; categoriesData: Record<string, string[]>; payments: string[] }) {', 'function TransactionsView({ transactions, onDelete, onDeleteGroup, onUpdate, onUpdateGroup, categoriesData, payments }: { transactions: Transaction[]; onDelete: (id: number) => void; onDeleteGroup: (groupId: string) => void; onUpdate: (transaction: Transaction) => void; onUpdateGroup: (groupId: string, total: number, note: string, payment: string) => void; categoriesData: Record<string, string[]>; payments: string[] }) {');
s = s.replace('  const saveEdit = (item: Transaction) => { const amount = Number(editAmount.replace(",", ".")); if (!amount || amount <= 0) { toast.error("Informe um valor válido."); return; } onUpdate({ ...item, amount, note: editNote, payment: editPayment }); setEditingId(null); toast.success("Lançamento atualizado."); };', '  const saveEdit = (item: Transaction, scope: "item" | "group") => { const amount = Number(editAmount.replace(",", ".")); if (!amount || amount <= 0) { toast.error("Informe um valor válido."); return; } if (scope === "group" && item.installmentGroupId) { onUpdateGroup(item.installmentGroupId, amount, editNote, editPayment); } else { onUpdate({ ...item, amount, note: editNote, payment: editPayment }); } setEditingId(null); toast.success(scope === "group" ? "Grupo parcelado atualizado." : "Parcela atualizada."); };');
s = s.replace('<div className="flex gap-2"><Button onClick={() => saveEdit(item)} className="h-10 rounded-lg bg-[#173f35] text-white">Salvar</Button><Button onClick={() => setEditingId(null)} variant="outline" className="h-10 rounded-lg border-[#dfe9e2]">Cancelar</Button></div>', '<div className="flex flex-wrap gap-2"><Button onClick={() => saveEdit(item, "item")} className="h-10 rounded-lg bg-[#173f35] text-white">Salvar parcela</Button>{item.installmentGroupId && <Button onClick={() => saveEdit(item, "group")} variant="outline" className="h-10 rounded-lg border-[#dfe9e2] text-[#98633c]">Salvar total do grupo</Button>}<Button onClick={() => setEditingId(null)} variant="outline" className="h-10 rounded-lg border-[#dfe9e2]">Cancelar</Button></div>');
s = s.replace('  const updateTransaction = (transaction: Transaction) => setTransactions((current) => current.map((item) => item.id === transaction.id ? transaction : item));', '  const updateTransaction = (transaction: Transaction) => setTransactions((current) => current.map((item) => item.id === transaction.id ? transaction : item));\n  const updateTransactionGroup = (groupId: string, total: number, note: string, payment: string) => setTransactions((current) => { const group = current.filter((item) => item.installmentGroupId === groupId).sort((a, b) => (a.installmentNumber ?? 0) - (b.installmentNumber ?? 0)); const values = splitInstallments(total, group.length); return current.map((item) => { const index = group.findIndex((entry) => entry.id === item.id); return index >= 0 ? { ...item, amount: values[index], note: note ? `Parcela ${index + 1}/${group.length} · ${note}` : `Parcela ${index + 1}/${group.length}`, payment } : item; }); });');
s = s.replace('<TransactionsView transactions={transactions} onDelete={deleteTransaction} onDeleteGroup={deleteTransactionGroup} onUpdate={updateTransaction} categoriesData={categoriesData} payments={payments} />', '<TransactionsView transactions={transactions} onDelete={deleteTransaction} onDeleteGroup={deleteTransactionGroup} onUpdate={updateTransaction} onUpdateGroup={updateTransactionGroup} categoriesData={categoriesData} payments={payments} />');
fs.writeFileSync(path, s);
